steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/step-alr-2020/api-image', '.' ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/step-alr-2020/api-image']
# Deploy container image to Cloud Run
# TODO deploy automatically
images:
- 'gcr.io/step-alr-2020/api-image'
